"""AI/low effort slop signals. These are heuristics, so even the strong ones
report as WARN (never a hard FAIL)- one alone nudges toward 'review',
several stacking up push a submission into 'flagged'"""

from __future__ import annotations

from datetime import datetime

from engine.types import SignalResult, Vector, Status, Severity, SEVERITY_POINTS

#thresholds (tunable)
SINGLE_DUMP_HIGH = 2000
SINGLE_DUMP_MED = 800
LOW_CADENCE_ADDITIONS = 1500
LOW_CADENCE_MAX_COMMITS = 8
BURST_WINDOW_SECONDS = 3600
BURST_MIN_COMMITS = 3

AI_README_MARKERS = [
    "as an ai language model",
    "as a large language model",
    "i cannot fulfill",
    "here is a readme",
    "here's a readme",
    "certainly! here",
    "this readme was generated",
    "this project was generated by",
    "lorem ipsum",
    "your project name here",
    "[your name]",
    "todo: add description",
]

#shared little builders
def _pass(sid, detail, evidence=None):
    return SignalResult(id=sid, vector=Vector.AI_SLOP, status=Status.PASS, severity=Severity.LOW, score=0, detail=detail, evidence=evidence or {})

def _insufficient(sid, detail):
    return SignalResult(id=sid, vector=Vector.AI_SLOP, status=Status.INSUFFICIENT, severity=Severity.LOW, score=0, detail=detail)

def _hit(sid, severity, detail, evidence):
    return SignalResult(id=sid, vector=Vector.AI_SLOP, status=Status.WARN, severity=severity, score=SEVERITY_POINTS[severity], detail=detail, evidence=evidence)

def _commit_times(commits):
    times = []
    for c in commits:
        commit = c.get("commit", {}) or {}
        ts = (commit.get("author") or {}).get("date") or (commit.get("committer") or {}).get("date")
        if not ts:
            continue
        try:
            times.append(datetime.fromisoformat(ts.replace("Z", "+00:00")))
        except ValueError:
            continue
    return times

#signals
def _ai_single_commit_dump(ctx) -> SignalResult:
    sid = "ai_single_commit_dump"
    if not ctx.commits or not ctx.commits_details:
        return _insufficient(sid, "Not enough commit data to assess")
    if ctx.commits_count > 2:
        return _pass(sid, f"{ctx.commits_count} commits- not a signal dump")
    adds = ctx.max_additions
    if adds >= SINGLE_DUMP_HIGH:
        return _hit(sid, Severity.HIGH, f"Only {ctx.commits_count} commit(s) but {adds} lines added- likely an AI/copy-paste dump", {"commits": ctx.commit_count, "additions": adds})
    if adds >= SINGLE_DUMP_MED:
        return _hit(sid, Severity.MEDIUM, f"Only {ctx.commits_count} commit(s) but {adds} lines added- possible code drop", {"commits": ctx.commit_count, "additions": adds})
    return _pass(sid, f"{ctx.commits_count} commit(s) {adds} lines- within normal range")

def ai_low_cadence_for_size(ctx) -> SignalResult:
    sid = "ai_low_cadence_for_size"
    if not ctx.commits or not ctx.commits_details:
        return _insufficient(sid, "Not enough commit data to assess")
    if not (3 <= ctx.commits_count <= LOW_CADENCE_MAX_COMMITS):
        return _pass(sid, "Commit history depth looks normal")
    if ctx.max_additions >= LOW_CADENCE_ADDITIONS:
        return _hit(sid, Severity.MEDIUM, f"{ctx.commits_count} commits but a {ctx.max_additions}- line push- thin history for the code size", {"commits": ctx.commits_count, "additions": ctx.max_additions})
    return _pass(sid, "Code size is consistent with commit count")

def ai_commit_burst(ctx) -> SignalResult:
    sid = "ai_commit_burst"
    times = _commit_times(ctx.commits)
    if len(times) < BURST_MIN_COMMITS:
        return _insufficient(sid, "Not enough timestamped commits to assess cadence")
    span = (max(times) - min(times)).total_seconds()
    if span <= BURST_WINDOW_SECONDS:
        minutes = int(span // 60)
        return _hit(sid, Severity.MEDIUM, f"All {len(times)} commits landed within ~{minutes} min- looks dumped, not built iteratively", {"commits": len(times), "span_commits": int(span)})
    return _pass(sid, "Commits are spread over time")

def ai_generic_readme(ctx) -> SignalResult:
    sid = "ai_generic_readme"
    if not ctx.readme_text:
        return _insufficient(sid, "No README text to scan")
    low = ctx.readme_text.lower()
    for marker in AI_README_MARKERS:
        if marker in low:
            return _hit(sid, Severity.LOw, f'README contains a generated/template tell: "{marker}".', {"marker": marker})
    return _pass(sid, "README shown no obvious AI/template tells")